### ISSUE TITLE
AKasAppl shutdown

### ISSUE THREAD

**Issue by shyifrah** [shyifrah/kas#19]
Upon shutdown via Ctrl+C (which calls the shutdown hook), the following message is issued twice:

`KAS base application termination in progress...`

**Comment by lechen26** [comment]
this issue happens also when running the MqServer within eclipse.

the problem is that on appLauncher within the launch method we call app.term which terminate the MqServer. but we've also registered as shutown hook for MqServer app, so this app.term being called twice.

we can either remove the Shutdown hook, or stop calling the actual app.term from the launcher. and just finish the app and the shutdown hook will handle the shutdown.

@shyifrah  let me know what you think.

**Comment by shyifrah** [comment]
Fixed
